language: python

python:
  - 2.7

sudo: required

services:
  - docker

env:
  global:
    - REPO=driesschulten/aws-java-circleci
    - secure: ss/Xnj++i4mTkWDjwEvtBkvVcnuF9rh1ndpCvNXe+FWrUhwv06FP6thWso8TObRd1aqE8WXiseJBsbPIR09cVyxG5cmYK2dokdvp/vHaCA3LT+QMG5nnDv7S9TDdOQKbZM7aTaoFWJZrbdTdImSFqstWv49qyzzqdT4vo2OAEuVOMGPXEjWfKokLOkWqcWb5X6e9JS/DJpn3fj8Z2S+yLwcLRc7MJt2gmop7WPU2z2eWuEXZu1NO3sfGbEBiLtdaa5/MN9tAKR7S5yDp2natQTDLBS5pZSTdkSeEqkEeNIkhWVd1isGzOlUgOtJ4nvEqgg4Qhtl0HxqooZDWyvyNBl+bwzB+Mtgc//9k+QYOj0hUjAQ0kCzYylbabY8muvgwiVRhwMIVB1ZWJSz19C3HHcsy2o+7jptXYJvyNoCeeTvzkf/TaOTkdS6wg73Mf4L1Ftl3vrnDDVTyd6OIFQKaJXUTW/lxDQQwxXJMOaRPd3WwVyFxe5nY0NVp4kS9DManZB0KvmMPL7QvIEyTzUYjP2A3nQWBFIu79Pz05pEMfUT+K/l/kBcNKCVb0Oi4/QoL33hPBl1x4YWxsi6VxX48dT9ItKwDSpUmOcVjTCigm3/S/gB+3ndpS7Rt8EulATb6L0eoYGPlDG8Q/8A5lbpek0HBoCcq+8CX58WWAZZSReI=
    - secure: orOZJ00Y+VpWp53P/abF0lCefh7tVE9XH+ysteO4hGPgbvfgVvJHVYOaJOv60DXzjXK/AzBvoe0ZlqO/pkJUGOMpGwUA3MnDfAKkAvTIu7tON7QBxYlaH7E7iXzM0k8rtf4+Tz4X/UaKGNLfwsyL9eVKDPx4AboNcoEouOfg4NKU5iLjSzlKSYZ20IKSt3pmH3TMF3ZzSXbv6j+L/GPM5/FnTtSw3sWN/gjRsCoBvOVKSYMimASJYzO7nfLaJCI/r6YTItlPZo2+S/XQo8f4TkUHG85FlxTddn7pFZWHgjsItPlhcmGzv9KUoNXC7e+76WJTuusVqHdgdoXpflNTFTeWlkCIb0zrGgsKaeinnICss5pdbPWJmn8mandhZuk273/75Z1/OvescboLAhcoKNt1bZZMYesghuVu5yrZuD3FIdfIgFvgRHjJ92xTcpqBVXfFRffSgF9kqJeY69vmIvgFi37NEgpyqle4anvulSk3uGlmY060r1kVv+HzYOlv/FpHO2mkVHc39UZBFPUlbwfL8Y8g9JF6Bpk6wmSkT34A9WbGlQMSuO6MJJefucH6ZRfJ9z6lBgx2k+qp/XKHySe8uSw1Zu7G1oTq2FLVxUNncpqkZNrKhMzmlX2kiLjNE0gs25OiUjoMKCEXxv+ZDbufCx0j1IA/OurX87Axi6o=

install:
  - docker build -t $REPO .

script: echo 'no tests!'

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker tag $REPO $REPO:latest
  - if [[ $TRAVIS_TAG ]]; then docker tag $REPO $REPO:$TRAVIS_TAG; fi
  - docker push $REPO
